// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ru":    &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"About":                             18,
	"Daemon started":                    28,
	"Daemon stopped":                    27,
	"Donations":                         19,
	"Free: %s Trash: %s":                26,
	"Help":                              17,
	"Last synchronized":                 6,
	"Light theme":                       13,
	"Notification service unavailable!": 21,
	"Notifications":                     14,
	"Open Yandex.Disk folder":           10,
	"Open Yandex.Disk in browser":       11,
	"Quit":                              20,
	"Settings":                          12,
	"Show daemon output":                9,
	"Start daemon":                      7,
	"Start on start":                    15,
	"Status: %s":                        24,
	"Stop daemon":                       8,
	"Stop on exit":                      16,
	"Synchronization finished":          30,
	"Synchronization started":           29,
	"Used: %s/%s":                       25,
	"Yandex.Disk daemon output":         22,
	"Yandex.Disk indicator":             0,
	"busy":                              3,
	"idle":                              1,
	"index":                             2,
	"none":                              4,
	"paused":                            5,
	"yd-go is the panel indicator for Yandex.Disk daemon.\n\n\tVersion: %s\n\nCopyleft 2017-%s Sly_tom_cat (slytomcat@mail.ru)\n\n\tLicense: GPL v.3\n\n": 23,
}

var en_USIndex = []uint32{ // 32 elements
	0x00000000, 0x00000016, 0x0000001b, 0x00000021,
	0x00000026, 0x0000002b, 0x00000032, 0x00000044,
	0x00000051, 0x0000005d, 0x00000070, 0x00000088,
	0x000000a4, 0x000000ad, 0x000000b9, 0x000000c7,
	0x000000d6, 0x000000e3, 0x000000e8, 0x000000ee,
	0x000000f8, 0x000000fd, 0x0000011f, 0x00000139,
	0x000001ce, 0x000001dc, 0x000001ee, 0x00000207,
	0x00000216, 0x00000225, 0x0000023d, 0x00000256,
} // Size: 152 bytes

const en_USData string = "" + // Size: 598 bytes
	"\x02Yandex.Disk indicator\x02idle\x02index\x02busy\x02none\x02paused\x02" +
	"Last synchronized\x02Start daemon\x02Stop daemon\x02Show daemon output" +
	"\x02Open Yandex.Disk folder\x02Open Yandex.Disk in browser\x02Settings" +
	"\x02Light theme\x02Notifications\x02Start on start\x02Stop on exit\x02He" +
	"lp\x02About\x02Donations\x02Quit\x02Notification service unavailable!" +
	"\x02Yandex.Disk daemon output\x04\x00\x02\x0a\x0a\x8e\x01\x02yd-go is th" +
	"e panel indicator for Yandex.Disk daemon.\x0a\x0a\x09Version: %[1]s\x0a" +
	"\x0aCopyleft 2017-%[2]s Sly_tom_cat (slytomcat@mail.ru)\x0a\x0a\x09Licen" +
	"se: GPL v.3\x02Status: %[1]s\x02Used: %[1]s/%[2]s\x02Free: %[1]s Trash: " +
	"%[2]s\x02Daemon stopped\x02Daemon started\x02Synchronization started\x02" +
	"Synchronization finished"

var ruIndex = []uint32{ // 32 elements
	0x00000000, 0x0000001f, 0x00000030, 0x00000045,
	0x00000060, 0x00000075, 0x00000080, 0x000000b8,
	0x000000da, 0x000000fe, 0x00000129, 0x00000153,
	0x00000182, 0x00000195, 0x000001ad, 0x000001c4,
	0x000001e9, 0x00000212, 0x0000021f, 0x00000239,
	0x00000254, 0x0000025f, 0x00000299, 0x000002bf,
	0x0000037d, 0x00000391, 0x000003b7, 0x000003e5,
	0x0000040b, 0x0000042b, 0x00000453, 0x00000481,
} // Size: 152 bytes

const ruData string = "" + // Size: 1153 bytes
	"\x02Индикатор Yandex.Disk\x02ожидание\x02индексация\x02синхронизация\x02" +
	"остановлен\x02пауза\x02Последние синхронизированные\x02Запустить утилит" +
	"у\x02Остановить утилиту\x02Показать вывод утилиты\x02Открыть каталог Ya" +
	"ndex.Disk\x02Открыть Yandex.Disk в браузере\x02Настройки\x02Светлая тема" +
	"\x02Уведомления\x02Запускать на старте\x02Остановить при выходе\x02Помощ" +
	"ь\x02Об индикаторе\x02Пожертвования\x02Выход\x02Сервис уведомлений недо" +
	"ступен!\x02Вывод утилиты Yandex.Disk\x04\x00\x02\x0a\x0a\xb7\x01\x02yd-" +
	"go это индикатор панели для утилиты Yandex.Disk.\x0a\x0a\x09Версия: %[1]" +
	"s\x0a\x0aCopyleft 2017-%[2]s Sly_tom_cat (slytomcat@mail.ru)\x0a\x0a\x09" +
	"Лицензия: GPL v.3\x02Статус: %[1]s\x02Использовано: %[1]s/%[2]s\x02Своб" +
	"одно: %[1]s Корзина: %[2]s\x02Утилита остановлена\x02Утилита запущена" +
	"\x02Синхронизация начата\x02Синхронизация закончена"

	// Total table size 2055 bytes (2KiB); checksum: E6D66B0E
